### ISSUE TITLE
CrossDomain issue

### ISSUE THREAD

**Issue by bernardodiasc** [DeuxHuitHuit/extension_downloader#4]
Tested on Sym2.4RC2

From console:

```
POST http://site/symphony/extension/extension_downloader/search/ 403 (Forbidden) symphony.min.js:26
Z.cors.a.crossDomain.send symphony.min.js:26
ab.extend.ajax symphony.min.js:25
ab.(anonymous function) symphony.min.js:25
search extension_downloader.js:80
```

I'm using a local server, not sure if the issue is related to this. Or it's possible to be a core issue with the Ajax API? Any thoughts?

**Comment by azzagazz** [comment]
hi,

i get the same error on a 2.6.2 install with extension downloader 1.1:

```
POST "http://testmailer.app/symphony/extension/extension_downloader/download/".
	Y.cors.a.crossDomain.send @ symphony.min.js:26
	_.extend.ajax @ symphony.min.js:25
	_.(anonymous function) @ symphony.min.js:25
	download @ extension_downloader.js:124
````

also a local install in a vagrant box. how can i fix this? 

thx
daniel

**Comment by nitriques** [comment]
Does your vagrant box can access the web ? I'll be out of the office for the next week, will check this ASAP.
