### ISSUE TITLE
Http error alert

### ISSUE THREAD

**Issue by johnpuddephatt** [DeuxHuitHuit/extension_downloader#6]
When I type into the search input, I get an HTTP error alert, and in the console there's a 404 for
`http://symphony.dev/symphonyextensions/extension_downloader/search/`

Should there be a `/` between symphony and extensions in that URL? I can do this by amending extension_downloader.js, but if I add the `/` in there I then still get a 404 but for `http://symphony.dev/symphony/extensions/extension_downloader/search/`.

(running symphony 2.6.7)

**Comment by nitriques** [comment]
Does the fix proposed in #5 fixes your issue ?

**Comment by johnpuddephatt** [comment]
Unfortunately not.

I still get a 404 in the console for `../extension_downloader/search/`.

Reverting to 1.1 it seems to works just fine.

**Comment by nitriques** [comment]
Ok thanks! Do you have xsrf enable in Symphony ?

**Comment by johnpuddephatt** [comment]
No, disabled it in config.php.

Having the same issue both locally and on the server with Sym 2.6.7… v1.1 works fine but 1.1.1 doesn’t.

**Comment by nitriques** [comment]
That's really weird...  I can't check what's up right now, but will try to do it this weekend

**Comment by nitriques** [comment]
This should be fixed in 1.1.2. Thanks!
